# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-08 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bedroom', models.BigIntegerField(blank=True)),
                ('Bathroom', models.DecimalField(blank=True, decimal_places=1, max_digits=4)),
                ('BasePrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TopPrice', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('Place_ID', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Estate_Name', models.CharField(max_length=60)),
                ('Altitude', models.FloatField()),
                ('Longtitude', models.FloatField()),
                ('Phone_Number', models.CharField(blank=True, max_length=60)),
                ('Address', models.CharField(max_length=100, unique=True)),
                ('City', models.CharField(max_length=30)),
                ('Zipcode', models.CharField(max_length=5)),
                ('Website', models.CharField(blank=True, max_length=255)),
                ('Crime_Grade', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Yelp_Grade', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Grade', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Yelp_Details',
            fields=[
                ('Name', models.CharField(max_length=100, primary_key=True)),
                ('Address', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=20, serialize=False)),
                ('Rating', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Yelp',
            fields=[
                ('yelp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='gtrent.Yelp_Details')),
                ('Place_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, serialize=False, to='gtrent.Property')),
                ('IsWalk', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='price',
            name='Place_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtrent.Property'),
        ),
    ]
