# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-15 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtrent', '0005_yelp_id'),
    ]

    operations = [

    ]
