# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-15 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtrent', '0008_auto_20160415_1941'),
    ]

    operations = [
    ]
