# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-15 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gtrent', '0010_auto_20160415_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yelp',
            name='Place_ID',
            field=models.ForeignKey(default='111', on_delete=django.db.models.deletion.CASCADE, serialize=False, to='gtrent.Property'),
        ),
    ]
