# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-15 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gtrent', '0011_auto_20160415_1951'),
    ]

    operations = [
    ]
