# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-16 02:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gtrent', '0015_auto_20160415_2036'),
    ]

    operations = [

    ]
