# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-16 03:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gtrent', '0016_auto_20160416_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yelp',
            name='Place_ID',
            field=models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, to='gtrent.Property'),
        ),
        migrations.AlterField(
            model_name='yelp',
            name='yelp',
            field=models.ForeignKey(default='111', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gtrent.Yelp_Details'),
        ),
    ]
