# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-25 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtrent', '0017_auto_20160416_0302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='Grade',
            new_name='Entertainment_Grade',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='Yelp_Grade',
            new_name='Food_Grade',
        ),
        migrations.RemoveField(
            model_name='price',
            name='TopPrice',
        ),
        migrations.RemoveField(
            model_name='price',
            name='id',
        ),
        migrations.AddField(
            model_name='price',
            name='ID',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='price',
            name='SquareFeet',
            field=models.FloatField(default=300, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='Gas_Grade',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='Place_ID',
            field=models.CharField(default='001', max_length=30, null=True),
        ),
    ]
