# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-25 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtrent', '0018_auto_20160425_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='cluster',
            field=models.IntegerField(null=True),
        ),
    ]
